export const COLOR_KEYWORDS = {
  'Blue': ['blue', 'navy', 'royal blue', 'cobalt'],
  'Sky Blue': ['sky blue', 'light blue', 'baby blue'],
  'Dark Blue': ['dark blue', 'navy blue', 'midnight blue'],
  'Black': ['black', 'noir'],
  'Grey': ['grey', 'gray', 'charcoal', 'silver', 'slate'],
  'Beige': ['beige', 'nude', 'sand', 'taupe', 'cream', 'ivory'],
  'White': ['white', 'off-white'],
  'Green': ['green', 'forest green', 'mint'],
  'Brown': ['brown', 'tan', 'khaki', 'camel'],
  'Pink': ['pink', 'rose', 'blush'],
  'Yellow': ['yellow', 'gold', 'mustard'],
  'Red': ['red', 'burgundy', 'crimson', 'wine'],
  'Orange': ['orange', 'rust', 'copper'],
  'Olive Green': ['olive green', 'olive'],
  'Maroon': ['maroon', 'burgundy'],
  'Denim': ['denim', 'denim blue']
};

export const STYLE_KEYWORDS = {
  casual: {
    categories: ['Tshirt', 'Hoodies', 'Jeans', 'Trackpants', 'Shoes'],
    description: 'Casual wear',
    keywords: ['casual', 'everyday', 'relaxed', 'comfortable', 'weekend']
  },
  formal: {
    categories: ['Shirt', 'Mens Accessories', 'Shoes', 'Sweater', 'Office wear'],
    description: 'Formal wear',
    keywords: ['formal', 'business', 'professional', 'office', 'work', 'dress']
  },
  'smart-casual': {
    categories: ['Shirt', 'Sweater', 'Jeans', 'Shoes'],
    description: 'Smart casual',
    keywords: ['smart casual', 'semi-formal', 'smart', 'classy']
  },
  athletic: {
    categories: ['Tshirt', 'Hoodies', 'Trackpants', 'Shoes', 'Sports'],
    description: 'Athletic wear',
    keywords: ['athletic', 'sport', 'gym', 'workout', 'active', 'fitness']
  },
  streetwear: {
    categories: ['Tshirt', 'Hoodies', 'Jeans', 'Shoes', 'Jacket'],
    description: 'Streetwear',
    keywords: ['streetwear', 'urban', 'street', 'hip hop', 'hype']
  },
  winter: {
    categories: ['Jacket', 'Sweater', 'Hoodies', 'Jeans'],
    description: 'Winter wear',
    keywords: ['winter', 'cold', 'warm', 'cozy']
  },
  summer: {
    categories: ['Tshirt', 'Trackpants', 'Shoes', 'Mens Accessories'],
    description: 'Summer wear',
    keywords: ['summer', 'light', 'breathable', 'cool']
  },
  traditional: {
    categories: ['Traditional', 'Shirt', 'Shoes', 'Mens Accessories'],
    description: 'Traditional / ethnic wear',
    keywords: ['traditional', 'ethnic', 'festive', 'indian', 'kurta', 'sherwani', 'indo western']
  }
};

export const CATEGORY_KEYWORDS = {
  'Tshirt': ['tshirt', 't-shirt', 't shirt', 'tee', 'tees'],
  'Shirt': ['shirt', 'button-up', 'button up', 'dress shirt', 'casual shirt', 'oxford', 'formal shirt'],
  'Jacket': ['jacket', 'coat', 'windbreaker', 'bomber', 'denim jacket', 'leather jacket', 'puffer'],
  'Hoodies': ['hoodie', 'hoodies', 'zip-up hoodie', 'zipper hoodie'],
  'Sweater': ['sweater', 'pullover', 'cardigan', 'knitwear', 'jumper'],
  'Sweatshirt': ['sweatshirt', 'crewneck', 'crew neck', 'fleece', 'sweat shirt'],
  'Jeans': ['jeans', 'denim', 'blue jeans', 'pants', 'trousers'],
  'Trackpants': ['trackpants', 'track pants', 'joggers', 'sweatpants', 'lower', 'bottoms'],
  'Shoes': ['shoes', 'sneakers', 'trainers', 'kicks', 'footwear'],
  'Mens Accessories': ['accessories', 'watch', 'watches', 'bag', 'bags', 'cap', 'caps', 'tie', 'belt', 'sunglasses', 'ring', 'rings', 'locket', 'lockets'],
  'Sports': ['sports', 'gym', 'athletic', 'workout', 'football', 'badminton'],
  'Office wear': ['office', 'formal', 'business', 'professional', 'corporate', 'suit', 'blazer', 'tuxedo'],

  'Skin care': ['skin care', 'skincare', 'facewash', 'face wash', 'moisturizer', 'moisturiser', 'sunscreen', 'serum', 'cleanser'],
  'Traditional': ['traditional', 'ethnic', 'festive', 'kurta', 'sherwani', 'dhoti', 'indo western', 'koti'],
  'Perfume': ['perfume', 'fragrance', 'cologne', 'scent', 'edt', 'edc', 'edp'],
  'Innerwear': ['innerwear', 'inner wear', 'trunks', 'boxers', 'vests', 'briefs', 'thermal', 'thermals', 'underwear', 'undergarments'],
  'Daily Essentials': ['daily essentials', 'essentials', 'storage', 'organizers', 'travel essentials', 'grooming tools', 'electronics', 'cleaning', 'care', 'everyday carry', 'home essentials']
};

export const SUBCATEGORY_KEYWORDS = {
  'Puffer': ['puffer', 'puffer jacket', 'padded jacket'],
  'Leather': ['leather', 'leather jacket'],
  'Varsity': ['varsity', 'varsity jacket', 'letterman'],
  'Bomber': ['bomber', 'bomber jacket'],
  'Biker': ['biker', 'biker jacket', 'motorcycle jacket'],
  'Half Jacket': ['half jacket', 'cropped jacket'],
  'Casual Jacket': ['casual jacket'],
  'Denim Jacket': ['denim jacket', 'jean jacket'],
  'Wind-cheater': ['windcheater', 'wind cheater', 'windbreaker'],
  'Zip Hoodie': ['zip hoodie', 'zipper hoodie', 'full zip'],
  'Pullover Hoodie': ['pullover', 'pullover hoodie', 'hoodie'],
  'V Neck Sweater': ['v neck', 'v-neck sweater'],
  'Round Neck Sweater': ['round neck', 'crew neck sweater'],
  'Turtle Neck Sweater': ['turtle neck', 'turtleneck'],
  'Polo Neck Sweater': ['polo neck sweater'],
  'Sweater Vest': ['sweater vest', 'vest'],
  'Cardigan': ['cardigan'],
  'Oversized Sweatshirt': ['oversized sweatshirt'],
  'Graphic Sweatshirt': ['graphic', 'printed sweatshirt'],
  'Normal Sweatshirt': ['sweatshirt', 'crewneck'],
  'Check Shirt': ['check', 'checked', 'plaid', 'checkered'],
  'Striped Shirt': ['stripe', 'striped'],
  'Printed Shirt': ['printed', 'print'],
  'Linen Shirt': ['linen', 'linen shirt'],
  'Textured Shirt': ['textured'],
  'Half Shirt': ['half sleeve', 'short sleeve'],
  'Solid Shirt': ['solid', 'plain'],
  'Shacket': ['shacket', 'shirt jacket'],
  'Formal Shirt': ['formal', 'dress shirt'],
  'Cuban Shirt': ['cuban', 'cuban collar'],
  'Wide Leg Jeans': ['wide leg', 'baggy jeans'],
  'Straight Fit Jeans': ['straight', 'straight fit'],
  'Cargo Jeans': ['cargo', 'cargo pants'],
  'Linen Pants': ['linen pants', 'linen trousers'],
  'Bootcut Jeans': ['bootcut', 'boot cut'],
  'Formal Pants': ['formal pants', 'dress pants', 'trousers'],
  'Chinos': ['chinos', 'khaki'],
  'Baggy Trackpants': ['baggy', 'loose fit'],
  'Cargo Trackpants': ['cargo trackpants'],
  'Straight Fit Trackpants': ['straight trackpants'],
  'Sneakers': ['sneakers', 'kicks'],
  'Sports Shoes': ['sports shoes', 'running shoes', 'trainers'],
  'Walking Shoes': ['walking shoes'],
  'Clogs': ['clogs'],
  'Boots': ['boots'],
  'Formal Shoes': ['formal shoes', 'dress shoes', 'oxford'],
  'Loafers': ['loafers'],
  'Canvas Shoes': ['canvas', 'canvas shoes'],
  'Polo Tshirt': ['polo', 'polo shirt'],
  'Oversized Tshirt': ['oversized tshirt', 'oversized t-shirt', 'oversized tee', 'oversized t shirt', 'oversized'],
  'Full Sleeve Tshirt': ['full sleeve', 'long sleeve'],
  'Gym Tshirt': ['gym tshirt', 'workout tshirt'],
  'V Neck Tshirt': ['v neck tshirt'],
  'Round Neck Tshirt': ['round neck tshirt'],
  'Printed Tshirt': ['printed tshirt', 'graphic tee'],
  'Normal Tshirt': ['normal tshirt', 'regular tshirt', 'basic tshirt', 'plain tshirt', 'tshirt', 'tee'],
  'Bags': ['bag', 'backpack', 'messenger', 'duffel'],
  'Caps': ['cap', 'hat', 'snapback', 'baseball cap'],
  'Watches': ['watch', 'wristwatch', 'timepiece'],
  'Tie': ['tie', 'necktie'],
  'Belt': ['belt'],
  'Sunglasses': ['sunglasses', 'shades'],
  'Rings': ['ring', 'rings'],
  'Lockets': ['locket', 'pendant', 'necklace'],
  'Sports Shorts': ['sports shorts'],
  'Sports Jacket': ['sports jacket', 'track jacket'],
  'Socks': ['socks'],
  'Sports Shoes General': ['sports shoes'],
  'Football Shoes': ['football shoes', 'cleats'],
  'Badminton Shoes': ['badminton shoes'],
  'Gym Tee': ['gym tee', 'workout shirt'],
  'Formal Pants Office': ['formal pants', 'office pants'],
  'Formal Shirts Office': ['formal shirt', 'office shirt'],
  'Suits': ['suit'],
  'Tuxedo': ['tuxedo', 'tux'],
  'Formal Shoes Office': ['formal shoes'],
  'Loafers Office': ['loafers'],
  'Blazers': ['blazer'],
  'Ties & Pocket Squares': ['tie', 'pocket square'],
  'Face Wash': ['face wash', 'facewash', 'cleanser'],
  'Moisturiser': ['moisturizer', 'moisturiser', 'lotion'],
  'Cleanser': ['cleanser'],
  'Sunscreen': ['sunscreen', 'spf'],
  'Serum': ['serum'],
  'Kurta': ['kurta'],
  'Koti': ['koti', 'nehru jacket'],
  'Pyjama': ['pyjama', 'pajama'],
  'Short Kurta': ['short kurta'],
  'Blazer Traditional': ['traditional blazer'],
  'Kurta Set': ['kurta set', 'kurta pyjama'],
  'Indo-western': ['indo western', 'fusion wear'],
  'EDT': ['edt', 'eau de toilette'],
  'EDC': ['edc', 'eau de cologne'],
  'EDP': ['edp', 'eau de parfum'],
  'Trunks': ['trunks', 'trunk'],
  'Boxers': ['boxers', 'boxer', 'boxer shorts'],
  'Vests': ['vests', 'vest', 'sleeveless'],
  'Briefs': ['briefs', 'brief'],
  'Thermal Top': ['thermal top', 'thermal shirt'],
  'Thermal Bottom': ['thermal bottom', 'thermal pants'],
  'Thermal Set': ['thermal set', 'thermal wear set'],
  'Storage & Organizers': ['storage', 'organizers', 'organizer', 'storage box'],
  'Travel Essentials': ['travel essentials', 'travel', 'luggage'],
  'Grooming Tools': ['grooming tools', 'grooming', 'trimmer', 'razor'],
  'Electronics': ['electronics', 'gadgets', 'tech'],
  'Cleaning & Care': ['cleaning', 'care', 'cleaning tools'],
  'Everyday Carry': ['everyday carry', 'edc', 'carry'],
  'Home Essentials': ['home essentials', 'home', 'household']
};
