export const COLOR_KEYWORDS = {
  'Blue': ['blue', 'navy', 'royal blue', 'cobalt'],
  'Sky Blue': ['sky blue', 'light blue', 'baby blue'],
  'Dark Blue': ['dark blue', 'navy blue', 'midnight blue'],
  'Black': ['black', 'noir'],
  'Grey': ['grey', 'gray', 'charcoal', 'silver', 'slate'],
  'Beige': ['beige', 'nude', 'sand', 'taupe', 'cream', 'ivory'],
  'White': ['white', 'off-white'],
  'Green': ['green', 'forest green', 'mint'],
  'Brown': ['brown', 'tan', 'khaki', 'camel'],
  'Pink': ['pink', 'rose', 'blush'],
  'Yellow': ['yellow', 'gold', 'mustard'],
  'Red': ['red', 'burgundy', 'crimson', 'wine'],
  'Orange': ['orange', 'rust', 'copper'],
  'Olive Green': ['olive green', 'olive'],
  'Maroon': ['maroon', 'burgundy'],
  'Denim': ['denim', 'denim blue']
};

export const STYLE_KEYWORDS = {
  casual: {
    categories: ['Tshirt', 'Hoodies', 'Jeans', 'Trackpants', 'Shoes'],
    description: 'Casual wear',
    keywords: ['casual', 'everyday', 'relaxed', 'comfortable', 'weekend']
  },
  formal: {
    categories: ['Shirt', 'Mens Accessories', 'Shoes', 'Sweater', 'Office wear'],
    description: 'Formal wear',
    keywords: ['formal', 'business', 'professional', 'office', 'work', 'dress']
  },
  'smart-casual': {
    categories: ['Shirt', 'Sweater', 'Jeans', 'Shoes'],
    description: 'Smart casual',
    keywords: ['smart casual', 'semi-formal', 'smart', 'classy']
  },
  athletic: {
    categories: ['Tshirt', 'Hoodies', 'Trackpants', 'Shoes', 'Sports'],
    description: 'Athletic wear',
    keywords: ['athletic', 'sport', 'gym', 'workout', 'active', 'fitness']
  },
  streetwear: {
    categories: ['Tshirt', 'Hoodies', 'Jeans', 'Shoes', 'Jacket'],
    description: 'Streetwear',
    keywords: ['streetwear', 'urban', 'street', 'hip hop', 'hype']
  },
  winter: {
    categories: ['Jacket', 'Sweater', 'Hoodies', 'Jeans'],
    description: 'Winter wear',
    keywords: ['winter', 'cold', 'warm', 'cozy']
  },
  summer: {
    categories: ['Tshirt', 'Trackpants', 'Shoes', 'Mens Accessories'],
    description: 'Summer wear',
    keywords: ['summer', 'light', 'breathable', 'cool']
  },
  traditional: {
    categories: ['Traditional', 'Shirt', 'Shoes', 'Mens Accessories'],
    description: 'Traditional / ethnic wear',
    keywords: ['traditional', 'ethnic', 'festive', 'indian', 'kurta', 'sherwani', 'indo western']
  }
};

export const CATEGORY_KEYWORDS = {
  'Tshirt': ['tshirt', 't-shirt', 't shirt', 'tee', 'tees'],
  'Shirt': ['shirt', 'button-up', 'button up', 'dress shirt', 'casual shirt', 'oxford', 'formal shirt'],
  'Jacket': ['jacket', 'coat', 'windbreaker', 'bomber', 'denim jacket', 'leather jacket', 'puffer'],
  'Hoodies': ['hoodie', 'hoodies', 'zip-up hoodie', 'zipper hoodie'],
  'Sweater': ['sweater', 'pullover', 'cardigan', 'knitwear', 'jumper'],
  'Sweatshirt': ['sweatshirt', 'crewneck', 'crew neck', 'fleece', 'sweat shirt'],
  'Jeans': ['jeans', 'denim', 'blue jeans', 'pants', 'trousers'],
  'Trackpants': ['trackpants', 'track pants', 'joggers', 'sweatpants', 'lower', 'bottoms'],
  'Shoes': ['shoes', 'sneakers', 'trainers', 'kicks', 'footwear'],
  'Mens Accessories': ['accessories', 'watch', 'watches', 'bag', 'bags', 'cap', 'caps', 'tie', 'belt', 'sunglasses', 'ring', 'rings', 'locket', 'lockets'],
  'Sports': ['sports', 'gym', 'athletic', 'workout', 'football', 'badminton'],
  'Office wear': ['office', 'formal', 'business', 'professional', 'corporate', 'suit', 'blazer', 'tuxedo'],

  'Skin care': ['skin care', 'skincare', 'facewash', 'face wash', 'moisturizer', 'moisturiser', 'sunscreen', 'serum', 'cleanser'],
  'Traditional': ['traditional', 'ethnic', 'festive', 'kurta', 'sherwani', 'dhoti', 'indo western', 'koti'],
  'Perfume': ['perfume', 'fragrance', 'cologne', 'scent', 'edt', 'edc', 'edp'],
  'Innerwear': ['innerwear', 'inner wear', 'trunks', 'boxers', 'vests', 'briefs', 'thermal', 'thermals', 'underwear', 'undergarments'],
  'Daily Essentials': ['daily essentials', 'essentials', 'storage', 'organizers', 'travel essentials', 'grooming tools', 'electronics', 'cleaning', 'care', 'everyday carry', 'home essentials']
};

export const SUBCATEGORY_KEYWORDS = {
  'Puffer': ['puffer', 'puffer jacket', 'padded jacket'],
  'Leather': ['leather', 'leather jacket'],
  'Varsity': ['varsity', 'varsity jacket', 'letterman'],
  'Bomber': ['bomber', 'bomber jacket'],
  'Biker': ['biker', 'biker jacket', 'motorcycle jacket'],
  'Half Jacket': ['half jacket', 'cropped jacket'],
  'Casual Jacket': ['casual jacket'],
  'Denim Jacket': ['denim jacket', 'jean jacket'],
  'Wind-cheater': ['windcheater', 'wind cheater', 'windbreaker'],
  'Zip Hoodie': ['zip hoodie', 'zipper hoodie', 'full zip'],
  'Pullover Hoodie': ['pullover', 'pullover hoodie', 'hoodie'],
  'V Neck Sweater': ['v neck', 'v-neck sweater'],
  'Round Neck Sweater': ['round neck', 'crew neck sweater'],
  'Turtle Neck Sweater': ['turtle neck', 'turtleneck'],
  'Polo Neck Sweater': ['polo neck sweater'],
  'Sweater Vest': ['sweater vest', 'vest'],
  'Cardigan': ['cardigan'],
  'Oversized Sweatshirt': ['oversized sweatshirt'],
  'Graphic Sweatshirt': ['graphic', 'printed sweatshirt'],
  'Normal Sweatshirt': ['sweatshirt', 'crewneck'],
  'Check Shirt': ['check', 'checked', 'plaid', 'checkered'],
  'Striped Shirt': ['stripe', 'striped'],
  'Printed Shirt': ['printed', 'print'],
  'Linen Shirt': ['linen', 'linen shirt'],
  'Textured Shirt': ['textured'],
  'Half Shirt': ['half sleeve', 'short sleeve'],
  'Solid Shirt': ['solid', 'plain'],
  'Shacket': ['shacket', 'shirt jacket'],
  'Formal Shirt': ['formal', 'dress shirt'],
  'Cuban Shirt': ['cuban', 'cuban collar'],
  'Wide Leg Jeans': ['wide leg', 'baggy jeans'],
  'Straight Fit Jeans': ['straight', 'straight fit'],
  'Cargo Jeans': ['cargo', 'cargo pants'],
  'Linen Pants': ['linen pants', 'linen trousers'],
  'Bootcut Jeans': ['bootcut', 'boot cut'],
  'Formal Pants': ['formal pants', 'dress pants', 'trousers'],
  'Chinos': ['chinos', 'khaki'],
  'Baggy Trackpants': ['baggy', 'loose fit'],
  'Cargo Trackpants': ['cargo trackpants'],
  'Straight Fit Trackpants': ['straight trackpants'],
  'Sneakers': ['sneakers', 'kicks'],
  'Sports Shoes': ['sports shoes', 'running shoes', 'trainers'],
  'Walking Shoes': ['walking shoes'],
  'Clogs': ['clogs'],
  'Boots': ['boots'],
  'Formal Shoes': ['formal shoes', 'dress shoes', 'oxford'],
  'Loafers': ['loafers'],
  'Canvas Shoes': ['canvas', 'canvas shoes'],
  'Polo Tshirt': ['polo', 'polo shirt'],
  'Oversized Tshirt': ['oversized tshirt', 'oversized t-shirt', 'oversized tee', 'oversized t shirt', 'oversized'],
  'Full Sleeve Tshirt': ['full sleeve', 'long sleeve'],
  'Gym Tshirt': ['gym tshirt', 'workout tshirt'],
  'V Neck Tshirt': ['v neck tshirt'],
  'Round Neck Tshirt': ['round neck tshirt'],
  'Printed Tshirt': ['printed tshirt', 'graphic tee'],
  'Normal Tshirt': ['normal tshirt', 'regular tshirt', 'basic tshirt', 'plain tshirt', 'tshirt', 'tee'],
  'Bags': ['bag', 'backpack', 'messenger', 'duffel'],
  'Caps': ['cap', 'hat', 'snapback', 'baseball cap'],
  'Watches': ['watch', 'wristwatch', 'timepiece'],
  'Tie': ['tie', 'necktie'],
  'Belt': ['belt'],
  'Sunglasses': ['sunglasses', 'shades'],
  'Rings': ['ring', 'rings'],
  'Lockets': ['locket', 'pendant', 'necklace'],
  'Sports Shorts': ['sports shorts'],
  'Sports Jacket': ['sports jacket', 'track jacket'],
  'Socks': ['socks'],
  'Sports Shoes General': ['sports shoes'],
  'Football Shoes': ['football shoes', 'cleats'],
  'Badminton Shoes': ['badminton shoes'],
  'Gym Tee': ['gym tee', 'workout shirt'],
  'Formal Pants Office': ['formal pants', 'office pants'],
  'Formal Shirts Office': ['formal shirt', 'office shirt'],
  'Suits': ['suit'],
  'Tuxedo': ['tuxedo', 'tux'],
  'Formal Shoes Office': ['formal shoes'],
  'Loafers Office': ['loafers'],
  'Blazers': ['blazer'],
  'Ties & Pocket Squares': ['tie', 'pocket square'],
  'Face Wash': ['face wash', 'facewash', 'cleanser'],
  'Moisturiser': ['moisturizer', 'moisturiser', 'lotion'],
  'Cleanser': ['cleanser'],
  'Sunscreen': ['sunscreen', 'spf'],
  'Serum': ['serum'],
  'Kurta': ['kurta'],
  'Koti': ['koti', 'nehru jacket'],
  'Pyjama': ['pyjama', 'pajama'],
  'Short Kurta': ['short kurta'],
  'Blazer Traditional': ['traditional blazer'],
  'Kurta Set': ['kurta set', 'kurta pyjama'],
  'Indo-western': ['indo western', 'fusion wear'],
  'EDT': ['edt', 'eau de toilette'],
  'EDC': ['edc', 'eau de cologne'],
  'EDP': ['edp', 'eau de parfum'],
  'Trunks': ['trunks', 'trunk'],
  'Boxers': ['boxers', 'boxer', 'boxer shorts'],
  'Vests': ['vests', 'vest', 'sleeveless'],
  'Briefs': ['briefs', 'brief'],
  'Thermal Top': ['thermal top', 'thermal shirt'],
  'Thermal Bottom': ['thermal bottom', 'thermal pants'],
  'Thermal Set': ['thermal set', 'thermal wear set'],
  'Storage & Organizers': ['storage', 'organizers', 'organizer', 'storage box'],
  'Travel Essentials': ['travel essentials', 'travel', 'luggage'],
  'Grooming Tools': ['grooming tools', 'grooming', 'trimmer', 'razor'],
  'Electronics': ['electronics', 'gadgets', 'tech'],
  'Everyday Carry': ['everyday carry', 'edc', 'carry'],
  'Home Essentials': ['home essentials', 'home', 'household']
};

export const BRAND_KEYWORDS = {
  // Traditional
  'Vastramay': ['vastramay'],
  'Invictus': ['invictus'],
  'House of Pataudi': ['house of pataudi', 'pataudi'],
  'Vastrado': ['vastrado'],
  'Kisah': ['kisah'],
  'DiwaS': ['diwas', 'diwas by manyavar'],
  'Tasva': ['tasva'],
  'Jompers': ['jompers'],
  'Anouk': ['anouk'],
  'Fabindia': ['fabindia'],

  // Innerwear
  'Jockey': ['jockey'],
  'XYXX': ['xyxx'],
  'Damensch': ['damensch'],
  'US Polo Assn': ['us polo', 'us polo assn', 'u.s. polo', 'uspa'],
  'H&M': ['h&m', 'hm', 'h & m'],
  'Calvin Klein': ['calvin klein', 'ck'],
  'Van Heusen': ['van heusen'],

  // Perfume
  'Skinn': ['skinn', 'skinn by titan'],
  'WildStone': ['wildstone', 'wild stone'],
  'Ajmal': ['ajmal'],
  'Bella Vita': ['bella vita', 'bellavita'],
  'Nautica': ['nautica'],
  'Jaguar': ['jaguar'],
  'Embark': ['embark'],
  'Guess': ['guess'],
  'Villain': ['villain'],
  'Park Avenue': ['park avenue'],
  'Davidoff': ['davidoff'],
  'Rasasi': ['rasasi'],
  'The Man Company': ['the man company', 'man company'],
  'Adilqadri': ['adilqadri'],

  // Skin Care
  'Minimalist': ['minimalist', 'beminimalist'],
  'Dot & Key': ['dot & key', 'dot and key', 'dot&key'],
  'Deconstruct': ['deconstruct'],
  'Lakmé': ['lakme', 'lakmé'],
  'The Derma Co': ['the derma co', 'derma co'],
  "POND'S": ["pond's", "ponds"],

  // Accessories & Others
  'Nike': ['nike'],
  'Adidas': ['adidas'],
  'Puma': ['puma'],
  'Gear': ['gear'],
  'Allen Solly': ['allen solly'],
  'Tommy Hilfiger': ['tommy hilfiger', 'tommy'],
  'Jack & Jones': ['jack & jones', 'jack and jones', 'jack&jones'],
  'Skybags': ['skybags'],
  'Titan': ['titan'],
  'Sonata': ['sonata'],
  'Fastrack': ['fastrack'],
  'Casio': ['casio'],
  'Timex': ['timex'],
  'Vincent Chase': ['vincent chase'],
  'John Jacobs': ['john jacobs'],
  'Yellow Chimes': ['yellow chimes'],
  'StyleCast': ['stylecast', 'stylecast x revolte'],
  'Salty': ['salty'],
  'Swashaa': ['swashaa'],
  'Voyage': ['voyage'],
  'Fashion Frill': ['fashion frill'],
  'Roadster': ['roadster'],
  'Vivity': ['vivity'],
  'Red Tape': ['red tape', 'redtape'],
  'Woodland': ['woodland'],
  'Provogue': ['provogue'],
  'Peter England': ['peter england'],
  'Asics': ['asics'],
  'Campus': ['campus'],
  'Red Chief': ['red chief'],
  'Thomas Crick': ['thomas crick'],
  'Liberty': ['liberty'],
  'Bata': ['bata'],
  'Converse': ['converse'],
  'Louis Stitch': ['louis stitch'],
  'Trenduty': ['trenduty'],
  'Spade Club': ['spade club'],
  'Hush Puppies': ['hush puppies'],
  'HRX': ['hrx', 'hrx by hrithik roshan'],
  'Maniac': ['maniac'],
  'Nobero': ['nobero'],
  'Bonkers Corner': ['bonkers corner', 'bonkers'],
  'Bene Kleed': ['bene kleed'],
  'Beyoung': ['beyoung'],
  'The Indian Garage Co': ['the indian garage co', 'indian garage co', 'tigc'],
  'Urbano Fashion': ['urbano fashion', 'urbano'],
  'Ben Martin': ['ben martin'],
  'Highlander': ['highlander'],
  'Snitch': ['snitch'],
  'Bewakoof': ['bewakoof'],
  'Pepe Jeans': ['pepe jeans', 'pepe'],
  'Glitchez': ['glitchez'],
  'Arrow': ['arrow'],
  'Studio Nexx': ['studio nexx'],
  'Bershka': ['bershka'],
  'Thomas Scott': ['thomas scott'],
  'Mast & Harbour': ['mast & harbour', 'mast and harbour'],
  'Decathlon': ['decathlon'],
  'Nivia': ['nivia'],
  'Hundred': ['hundred'],
  'Technosport': ['technosport'],
  'The Bear House': ['the bear house', 'bear house'],
  'Mr Bowerbird': ['mr bowerbird', 'bowerbird'],
  'Peluche': ['peluche'],
  'Blackberrys': ['blackberrys', 'blackberry'],
  'Campus Sutra': ['campus sutra'],
  'Powerlook': ['powerlook'],
  'Wrogn': ['wrogn'],
  'Dennis Lingo': ['dennis lingo'],
  'Rare Rabbit': ['rare rabbit'],
  'Banana Club': ['banana club', 'bananna club'],
  'Aeropostale': ['aeropostale'],
  'Zara': ['zara'],
  'Here & Now': ['here & now', 'here and now'],
  'Trendyol': ['trendyol']
};
