export const PRODUCT_CATEGORIES = [
    'Jacket', 'Hoodies', 'Sweater', 'Sweatshirt', 'Shirt', 'Jeans', 'Trackpants', 'Shoes',
    'Tshirt', 'Mens Accessories', 'Sports', 'Office Wear', 'Innerwear', 'Daily Essentials',
    'Body Care', 'Traditional', 'Perfume',
];

export const PRODUCT_SUBCATEGORIES = {
    'Jacket': ['Puffer', 'Leather', 'Varsity', 'Bomber', 'Biker', 'Half', 'Denim', 'Hiking', 'Faux', 'Overcoat', 'Printed', 'Reversible', 'Tailored', 'Cotton'],
    'Hoodies': ['Zip Hoodie', 'Regular Fit', 'Printed'],
    'Sweater': ['V-Neck', 'Round Neck', 'Turtle Neck', 'Polo Neck', 'Sweater Vest', 'Cardigan', 'Zipper', 'Printed'],
    'Sweatshirt': ['Oversized', 'Printed', 'Pullover', 'Zipper'],
    'Shirt': ['Check', 'Striped', 'Printed', 'Linen', 'Textured', 'Half Sleeve', 'Solid', 'Shacket', 'Formal Shirt'],
    'Jeans': ['Wide Leg', 'Straight Fit', 'Cargo', 'Linen Pants', 'Bootcut', 'Chinos', 'Korean Pants', 'Formal Pants', 'Corduroy', 'Baggy'],
    'Trackpants': ['Baggy', 'Cargo'],
    'Shoes': ['Sneakers', 'Clogs', 'Boots', 'Loafers', 'Canvas', 'Formal Shoes', 'Ethnic Shoes', 'Sports Shoes', 'Football Shoes', 'Badminton Shoes'],
    'Tshirt': ['Polo', 'Oversized', 'Full Sleeve', 'Regular Fit', 'Gym Tee', 'Football Jersey'],
    'Mens Accessories': ['Bags', 'Caps', 'Watches', 'Belts', 'Sunglasses', 'Rings', 'Chains'],
    'Sports': ['Shorts', 'Sports Jacket', 'Socks', 'Sports Shoes', 'Football Shoes', 'Badminton Shoes', 'Gym Tee', 'Football Jersey'],
    'Office Wear': ['Formal Shirts', 'Formal Pants', 'Formal Shoes', 'Suits', 'Loafers', 'Blazers', 'Ties & Pocket Squares'],
    'Body Care': ['Face Wash', 'Moisturiser', 'Sunscreen', 'Serum', 'Roll-On', 'Body Wash', 'Hair Oil', 'Shampoo'],
    'Traditional': ['Kurta', 'Nehru Jacket', 'Pyjama', 'Short Kurta', 'Blazer', 'Indo-Western', 'Ethnic Shoes'],
    'Perfume': ['Luxurious', 'Under Budget'],
    'Innerwear': ['Trunks', 'Vests', 'Boxers', 'Thermal Wear'],
    'Daily Essentials': ['Storage & Organizers', 'Travel Essentials', 'Grooming Tools', 'Electronics', 'Cleaning & Care', 'Everyday Carry', 'Home Essentials'],
};

export const ALL_SUBCATEGORIES = Object.values(PRODUCT_SUBCATEGORIES).flat();

export const PRODUCT_COLORS = [
    'Black', 'Jet Black', 'Charcoal', 'Graphite', 'Gunmetal', 'Onyx', 'Ebony',
    'Gray', 'Grey', 'Light Gray', 'Dark Gray', 'Heather Gray', 'Slate', 'Pewter', 'Steel',
    'Silver', 'White', 'Off-White', 'Ivory', 'Cream', 'Alabaster', 'Bone',
    'Beige', 'Sand', 'Tan', 'Camel', 'Khaki', 'Taupe', 'Stone', 'Oatmeal', 'Mushroom',
    'Brown', 'Mocha', 'Cocoa', 'Chestnut', 'Walnut', 'Mahogany', 'Chocolate',
    'Saddle', 'Sepia', 'Sienna', 'Terracotta', 'Rust', 'Copper', 'Bronze', 'Brass', 'Umber',
    'Red', 'Brick Red', 'Burgundy', 'Maroon', 'Wine', 'Oxblood', 'Crimson', 'Scarlet',
    'Cherry', 'Ruby', 'Garnet', 'Berry', 'Raspberry', 'Coral', 'Salmon', 'Peach',
    'Apricot', 'Blush', 'Rose', 'Dusty Pink', 'Fuchsia', 'Magenta', 'Pink',
    'Orange', 'Tangerine', 'Amber', 'Ochre', 'Mustard', 'Saffron', 'Gold', 'Metallic Gold',
    'Yellow', 'Canary', 'Dandelion', 'Lemon', 'Marigold',
    'Green', 'Olive', 'Army Green', 'Khaki Green', 'Moss', 'Fern', 'Pistachio', 'Sage',
    'Mint', 'Seafoam', 'Emerald', 'Jade', 'Kelly Green', 'Hunter Green', 'Forest Green',
    'Lime', 'Chartreuse', 'Neon Green', 'Olive Green',
    'Blue', 'Navy', 'Royal Blue', 'Cobalt', 'Indigo', 'Azure', 'Sky Blue', 'Baby Blue',
    'Cornflower', 'Periwinkle', 'Turquoise', 'Teal', 'Aqua', 'Cyan', 'Sea Blue', 'Dark Blue',
    'Purple', 'Violet', 'Plum', 'Eggplant', 'Aubergine', 'Lavender', 'Lilac', 'Mauve',
    'Metallic Silver', 'Bronzed', 'Copper Metallic', 'Rose Gold',
    'Pastel Blue', 'Pastel Pink', 'Pastel Green', 'Pastel Yellow', 'Pastel Purple',
    'Dusty Blue', 'Dusty Rose', 'Muted Olive', 'Washed Denim', 'Denim Blue', 'Indigo Wash', 'Denim',
    'Neon Pink', 'Neon Yellow', 'Neon Orange', 'Neon Blue', 'Highlighter Green',
    'Off Black', 'Stonewash', 'Vintage Wash', 'Distressed Blue',
];

export const PRODUCT_BRANDS = [
    'Adidas', 'ADILQADRI', 'Aeropostale', 'Ahmed Al Maghribi', 'Ajmal', 'Allen Solly', 'Anouk', 'Arrow',
    'Armani', 'Armani Beauty', 'Asics', 'Azzaro', 'Bajaj', 'Bata', 'Bewakoof', 'Bene Kleed', 'Bershka',
    'Beyoung', 'Bella Vita', 'Being Human', 'Blackberrys', 'Campus', 'Campus Sutra', 'Cantabil', 'Casio',
    'Cetaphil', 'Chemist at Play', 'Columbia', 'Converse', 'Creed', 'Crocs', 'Damensch', 'DaMENSCH',
    'Davidoff', 'Decathlon', 'Denver', 'Dior', 'Dolce & Gabbana', 'Dot & Key', 'DRIP SPOILER', 'Ducati',
    'Embark', 'Fastrack', 'Fashion Frill', 'French Connection', 'Fuaark', 'Gap', 'GAP', 'Gear', 'Glitchez',
    'Goatter', 'Guess', 'H&M', 'Here & Now', 'HERE&NOW', 'Hermès', 'Highlander', 'House of Pataudi',
    'HRX by Hrithik Roshan', 'HRX', 'Hundred', 'Indulekha', 'Invictus', 'Jack & Jones', 'Jean Paul Gaultier',
    'Jockey', 'Kalpraag', 'KISAH', 'Lakmé', 'Lattafa', 'Leather Retail', 'Levi\'s', 'Liberty',
    'Louis Philippe', 'Louis Stitch', 'L\'Oréal', 'Maniac', 'Marks & Spencer', 'Mast & Harbour', 'Minimalist',
    'Monkstory', 'Monte Carlo', 'Mr Bowerbird', 'Mutaqinoti', 'Navratna', 'Nautica', 'Nike', 'Nivia',
    'Nobero', 'Paco Rabanne', 'Parachute', 'Park Avenue', 'PELUCHE', 'Peluche', 'Peter England',
    'Peter England Elite', 'Ponds', 'Pond\'s', 'Powerlook', 'Provogue', 'PUMA', 'Puma', 'PUMA Motorsport',
    'Rare Rabbit', 'Raymond', 'Red Tape', 'Replica', 'Maison Margiela', 'Roadster', 'Royal Enfield',
    'Salty', 'Selected', 'See Designs', 'Skinn by Titan', 'Skybags', 'Snitch', 'SNITCH', 'Sonata',
    'Spade Club', 'StyleCast x Revolte', 'StyleCast', 'Studio Nexx', 'Supersox', 'Swashaa',
    'The Bear House', 'The Derma Co', 'The Ethnic Co', 'TheEthnic.Co', 'The Indian Garage Co',
    'The Indian Garage Co.', 'The Man Company', 'The Souled Store', 'Thomas Crick', 'Titan', 'Tommy Hilfiger',
    'Trendyol', 'Trenduty', 'TBOJ', 'U.S. Polo Assn.', 'US Polo', 'United Colors of Benetton',
    'Urbano Fashion', 'Ustraa', 'Van Heusen', 'VAN Heusen', 'Vastrado', 'Vastramay', 'Vector X',
    'Versace', 'Vincent Chase', 'Vivity', 'Voyage', 'Wild Stone', 'Wrogn', 'XYXX', 'Yellow Chimes',
    'Yoho', 'Yves Saint Laurent', 'MAX', 'Manyavar', 'Diwas by Manyavar', 'Dennison', 'Banana Club',
    'Tortoise', 'Pierre Carlo', 'Beardo', 'Villain', 'Nivea', 'Dove', 'Lux', 'Pears', 'Timex', 'Woodland',
    'Pepe Jeans'
].sort();

export const BRAND_CATEGORIES = {
    'Traditional': ['Vastramay', 'House of Pataudi', 'KISAH', 'Anouk', 'Invictus', 'Arrow', 'Vastrado', 'Kalpraag', 'TheEthnic.Co', 'Blackberrys', 'Peter England Elite', 'Manyavar', 'Louis Stitch', 'Diwas by Manyavar', 'See Designs'],
    'Innerwear': ['Damensch', 'DaMENSCH', 'XYXX', 'U.S. Polo Assn.', 'Jockey', 'Pepe Jeans'],
    'Perfume': ['Lattafa', 'Embark', 'Ustraa', 'Tommy Hilfiger', 'Maison Margiela', 'Azzaro', 'Jean Paul Gaultier', 'Creed', 'Armani', 'Versace', 'Yves Saint Laurent', 'Dior', 'Paco Rabanne', 'Hermès', 'Dolce & Gabbana', 'Armani Beauty', 'Guess', 'Davidoff', 'Ahmed Al Maghribi', 'Skinn by Titan', 'Bella Vita', 'Nautica', 'Wild Stone', 'Ajmal', 'Beardo', 'Villain', 'Denver', 'Fastrack', 'Adidas', 'ADILQADRI'],
    'Body Care': ['Cetaphil', 'Minimalist', 'Pond\'s', 'Dot & Key', 'Lakmé', 'The Derma Co', 'Nivea', 'Chemist at Play', 'The Man Company', 'Indulekha', 'Navratna', 'Parachute', 'Bajaj', 'L\'Oréal', 'Dove', 'Lux', 'Pears'],
    'Mens Accessories': ['Gear', 'PUMA', 'Skybags', 'Tommy Hilfiger', 'Jack & Jones', 'Nike', 'Adidas', 'Titan', 'Fastrack', 'Peter England', 'Timex', 'Van Heusen', 'Sonata', 'Casio', 'Vincent Chase', 'Voyage', 'Red Tape', 'Provogue', 'Woodland', 'Allen Solly', 'Roadster', 'Yellow Chimes', 'H&M', 'StyleCast x Revolte', 'Salty', 'Swashaa', 'Fashion Frill', 'Vivity'],
    'Shoes': ['Adidas', 'PUMA', 'Nike', 'Red Tape', 'U.S. Polo Assn.', 'HRX by Hrithik Roshan', 'Campus', 'Roadster', 'Thomas Crick', 'Louis Stitch', 'Louis Philippe', 'Liberty', 'Bata', 'Monkstory', 'House of Pataudi', 'Invictus', 'Cantabil', 'Crocs', 'Yoho', 'Trenduty', 'Spade Club', 'Converse'],
    'Trackpants': ['Bene Kleed', 'Nobero', 'Maniac', 'H&M', 'HRX'],
    'Jeans': ['Studio Nexx', 'Roadster', 'Glitchez', 'Bene Kleed', 'The Indian Garage Co.', 'Bershka', 'Urbano Fashion', 'Bewakoof', 'Arrow', 'Beyoung', 'Mr Bowerbird', 'H&M'],
    'Sports': ['Asics', 'Hundred', 'Nivia', 'HRX', 'Decathlon', 'PUMA', 'Fuaark', 'Adidas', 'Vector X', 'Jockey', 'Supersox', 'Nike'],
    'Office Wear': ['Beyoung', 'Rare Rabbit', 'Arrow', 'Louis Stitch', 'Liberty', 'Bata', 'Thomas Crick', 'Monkstory', 'Louis Philippe', 'Raymond', 'Blackberrys', 'House of Pataudi', 'Invictus', 'Roadster', 'Cantabil', 'H&M', 'Selected', 'Peluche', 'Mutaqinoti'],
    'Tshirt': ['Highlander', 'Roadster', 'XYXX', 'Powerlook', 'Campus Sutra', 'Nobero', 'SNITCH', 'PUMA', 'H&M', 'Jack & Jones', 'MAX', 'United Colors of Benetton', 'Levi\'s', 'Bewakoof', 'U.S. Polo Assn.', 'Fuaark', 'Nike', 'Adidas'],
    'Shirt': ['Vastrado', 'Dennis Lingo', 'Campus Sutra', 'Roadster', 'The Indian Garage Co.', 'Mast & Harbour', 'Highlander', 'HERE&NOW', 'Trendyol', 'Nobero', 'GAP', 'H&M', 'The Souled Store', 'Dennison', 'The Bear House', 'Mr Bowerbird', 'Banana Club'],
    'Sweatshirt': ['Roadster', 'H&M', 'Highlander', 'Trendyol', 'Campus Sutra', 'Maniac', 'Glitchez', 'United Colors of Benetton', 'Bershka', 'U.S. Polo Assn.', 'Wrogn', 'The Souled Store', 'Park Avenue', 'HRX by Hrithik Roshan'],
    'Sweater': ['Trendyol', 'H&M', 'Mast & Harbour', 'StyleCast', 'Bershka', 'Highlander', 'Roadster', 'Marks & Spencer', 'XYXX', 'Mr Bowerbird', 'Campus Sutra', 'Wrogn', 'French Connection', 'The Indian Garage Co.', 'Monte Carlo', 'SNITCH', 'Peter England Casuals', 'Rare Rabbit', 'Cantabil', 'Glitchez', 'The Souled Store', 'Bewakoof', 'Jack & Jones'],
    'Hoodies': ['H&M', 'Trendyol', 'Bershka', 'Glitchez', 'Roadster', 'Highlander', 'PUMA', 'Urbano Fashion'],
    'Jacket': ['Bershka', 'H&M', 'Highlander', 'Tortoise', 'Roadster', 'TBOJ', 'Goatter', 'HERE&NOW', 'Jack & Jones', 'The Souled Store', 'SNITCH', 'Campus Sutra', 'Wrogn', 'Aeropostale', 'The Bear House', 'XYXX', 'Mast & Harbour', 'DRIP SPOILER', 'StyleCast x Revolte', 'Glitchez', 'Leather Retail', 'Pierre Carlo', 'Royal Enfield', 'PUMA Motorsport', 'Ducati', 'Decathlon', 'Columbia', 'Rare Rabbit', 'Monte Carlo', 'Invictus', 'U.S. Polo Assn.', 'Being Human', 'The Indian Garage Co.', 'HRX by Hrithik Roshan'],
};
